language: python
addons:
  firefox: "67.0"
python:
  - "3.6"
  - "nightly"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
services:
  - xvfb
before_script:
  - "export DISPLAY=:99.0"
  - sleep 3 # give xvfb some time to start
install:
  - "pip install pytest"
  - "pip install pytest-cov"
  - "pip install -r requirements.txt"
script:
  - coverage run manage.py test
after_success:
  - codecov
